### ISSUE TITLE
Inicio y creación de usuarios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#1]
Se debe de crear una vista para que los administradores puedan iniciar sesión. Una vez esté esta vista creada, debe de haber otra donde el administrador tenga permitido mediante un formulario crear un nuevo usuario.
Esta segunda vista tendrá conexión con la segunda issue porque se reutilizará para que además el administrador tenga más opciones disponibles además de crear los usuarios nuevos.

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RF-01 | Primario | Gestión de miembros. | El sistema deberá permitir al administrador listar, crear, editar, dar de baja/alta a miembros de la base de datos.
RU-01 | Primario | Facilidad de usabilidad. | El sistema deberá ser seguro, accesible e intuitivo.

</body>
</html>

**Comment by lNoelia** [comment]
@juaalvcam ¿puedes actualizar el estado de esta tarea ? ¿Estás teniendo algún problema?

**Comment by rosmolarr** [comment]
No hay boton del login, de logout y tampoco el campo de contraseña esta oculto, se ve tal cual como un campo normal. Esta tarea va a cambiar de asignado por la tardanza en hacerla.

**Comment by lNoelia** [comment]
Además de lo que ha comentado rosa, cuando se creen los roles de administrador, revisar que en las páginas de administración solo pueden acceder los administradores.

**Comment by rubsuadav** [comment]
Para lo comentado por noelia puedo tener una solución y es que react-router dom te permite ocultar tales URLs según el rol, pasé hará 15 días un vídeo muy útil de implementar un login/logout usando react. Puede que nos sirva de ayuda

**Comment by Josdelsan** [comment]
El navegador no guarda cookies que vengan de un origen distinto (cross domain cookies). Para intentar solventar eso se ha configurado en el servidor de frontend un proxy que apunta al despliegue del backend. En local funciona, desplegando el backend no.

Antes de optar por configurar un proxy se han probado muchas formas distinta de permitir las cross domain cookies sin exito tanto cambiando la configuración del frontend como backend.

La otra opción sería cambiar a autentiación JWT pero seguiría sin funcionar los token csrf.

Una vez se solucione eso se va a refactorizar todo el código para adaptarlo.

**Comment by Josdelsan** [comment]
Se ha adaptado todo el código y añadido validaciones al formulario del inicio de sesión. Faltan tomar algunas decisiones de donde vamos a poner los botones de login y temas de estilo.

Sería conveniente refactorizar para poner orden en los endpoint del frontend ya que no siguen una norma común. Doy por hecho que hay todavía algún fallo que no se ha detectado, hay que vigilar para comprobar que el login está a prueba de bombas .

De momento no hay implementada lógica de roles en el frontend, sólo distingue de logeado y no logeado. En el backend si distingue entre administradores y no adminstradores.

**Comment by rubsuadav** [comment]
Yo imagino que con la tarea de gestión de usuarios que ha echo nico podemos coger dicho usuario y comprobar si es admin con una propiedad que tiene de is_admin y ya jugar con eso

**Comment by rubsuadav** [comment]
Con respecto a lo del login a prueba de bombas ahora probaré yo que funcione perfectamente

**Comment by Josdelsan** [comment]
La propiedad de is_admin la tiene la clase user de django, realmente desde el frontend nosotros solo tenemos los token. Habría que ver la manera de traerse el tipo de usuario desde el backend. Aún así, ahora mismo no nos hace falta. Sería hacer cambios al AtuhContextProvider en todo caso.

Lo que es más propenso a fallo del login es el tiempo de vida del token de acceso y que no se renueve bien con el refresh token. Diría que faltan cubrir algunos cosas específicos al interceptar las respuestas del backend, hay que ir probando e ir solucionando los errores cuando vayan surgiendo.

**Comment by rubsuadav** [comment]
Se han adaptado los endpoints del administrador acorde a la tarea implementada del login
