### ISSUE TITLE
Mapa de recursos y su gestión

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#12]
Tarea backend: ISPP-2023-NGO-P3/backend-aiding#10

Realizar un mapa interactivo donde se muestren puntos de interés que el usuario administrador puede insertar. **Valorar** OpenStreetMap como alternativa open-source a Google Maps. Haciendo consultas quizas a partir de la ciudad y la calle podemos ahorrarnos tener que meter coordenadas. Incluso puede que pulsando en el mapa nos devuelva las coordenadas y la calle.

<html>
<body>

ID | Prioridad | Título | Descripción
-- | -- | -- | --
RF-14 | Primario | Gestionar recursos (mapa). | El sistema debe permitir crear recursos con puntos de interés, los editen, los listen y los eliminen.
RI-05 | Primario | Recursos (Mapa). | El sistema debe almacenar información de los recursos con: titulo, descripción, calle, numero, ciudad, comentarios adicionales, coordenadas x e y.

</body>
</html>

Algunos prototipos no funcionales de referencia.

![image](https://user-images.githubusercontent.com/74303153/222378467-5972b127-77be-428f-a80f-240b6daf277e.png)

![image](https://user-images.githubusercontent.com/74303153/222378512-f07a7d66-227b-454a-9895-03409d4f2b32.png)

**Comment by marinaramirofde** [comment]
Se van a incluir a los recursos los atributos "fecha inicio" y "fecha fin" para tener un control de aquellos tomados como eventos puntuales.

**Comment by lNoelia** [comment]
¿@marinaramirofde puedes actualizar el estado de esta tarea ? ¿Qué le falta? ¿Ha ocurrido algún problema?

**Comment by marinaramirofde** [comment]
Hecho: 
- CRUD de recursos (Admin).
- Listado de recursos .
- Vista individual de recursos con mapa asociado.

Por actualizar:
- Nuevos atributos -> Teléfono de contacto y tipo de recurso.

Por arreglar:
- Bug del mapa => Al recorrer los datos de los recursos y colocar más de un marcador al mapa, falla.

Posible ampliación:
- Filtrado de recursos por tipo en la vista de mapa y listado de recursos.

**Comment by marinaramirofde** [comment]
Hecho:

CRUD de recursos (Admin).
Listado de recursos .
Vista individual de recursos con mapa asociado.
Teléfono de contacto y tipo de recurso. (AGREGADOS)

Por arreglar:

Bug del mapa => Al recorrer los datos de los recursos y colocar más de un marcador al mapa, falla.
Da error al agregar los nuevos atributos. ERROR 500 ?¿

Posible ampliación:

Filtrado de recursos por tipo en la vista de mapa y listado de recursos.

**Comment by marinaramirofde** [comment]
Problema del back, no se puede hacer create o edit por el atributo resources_type.

**Comment by rubsuadav** [comment]
Esta actualizado ya

**Comment by rubsuadav** [comment]
Hazre pull de develop

**Comment by lNoelia** [comment]
Semana 8 - Arreglar pequeños fallos ( recursos desplegados al entrar a la página)
