### ISSUE TITLE
Registro de voluntarios - frontend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#19]
Se pide realizar CRUD del módulo voluntarios. En esta tarea no se realizarán los turnos.

![Image](https://user-images.githubusercontent.com/80246352/225655409-da824e56-f97a-4963-9e1f-01f748a285aa.png)

Además de esos atributos se pide añadir un enumerado llamado conocimientos, para poder administrar estos datos con mayor facilidad. Este enumerado constará de conocimientos sobre:
- informática
- manejar un camión
- gestionar almacén

Actualmente vamos a tomar como si los voluntarios no pudieran loguearse al tratarse de una tarea más compleja.

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RI-08 | Primario | Voluntarios. | El sistema debe registrar de cada voluntario: número de voluntario, nombre y apellidos, situación (a la espera, en trámite y los demás lo tienen que definir), NIF, código postal, fecha de nacimiento, teléfono, email, sabe de informática, sabe de manejar un camión, sabe gestionar almacén y otros conocimientos, si está activo y el rol (voluntario de recogida, capitán y supervisor). Además, dispondrá de otro campo llamado observaciones para dejar comentado lo que sea necesario.

</body>
</html>

**Comment by lNoelia** [comment]
La tarea se me está complicando un poco y no la voy a tener para hoy, espero tenerla para mañana, hay algunos fallitos en el backend que han dificultado el progreso pero ya han sido informados. He hecho la vista de list, la del show está a medias, pero no hay problema ninguno con ellas. Solo me faltan la vista del edit y del post ya que hay errores en el backend que me producen errores a la hora de hacer post/put.

**Comment by lNoelia** [comment]
Ya se pueden crear voluntarios, mostrarlos, listarlos etc pero a la hora de editarlo hay un problema al mostrar los valores booleanos y al actualizarlo. Voy a tomarme un descanso e intentar acabarla. Además he actualizado algunas cosas del backend que daban error

**Comment by lNoelia** [comment]
Tarea completada y pull request a develop hecha, esperando respuesta de los QA para asegurar la calidad del incremento
