### ISSUE TITLE
Gestión de usuarios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#2]
Esta issue está muy ligada a la anterior (Inicio y creación de usuarios). Reutilizando la misma vista que tiene el administrador una vez logueado para poder crear un nuevo usuario, se debe de poder editar, o eliminar usuarios (está definido como dar de baba, tengo que aclarar esto porque a lo mejor no los borramos, solo los ponemos como inactivos o algo así para poder activarlos como un boolean en el Back).
<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RF-01 | Primario | Gestión de miembros. | El sistema deberá permitir al administrador listar, crear, editar, dar de baja/alta a miembros de la base de datos.

</body>
</html>

**Comment by nicsanmen** [comment]
acabo de actualizar la issue, está practicamente todo hecho (me ha llevado más de lo que me gustaría) pero creo que no sé hacer bien la conexión con el back en cuanto a la variable is_admin, no sé como hacer un get o un post de esa variable o no sé que estoy haciendo mal, porque el resto de atributos los recupera bien en el list de los usuarios. Lo intento solucionar y sino pido ayuda para ver si alguien me echa un cable y se sube.
