### ISSUE TITLE
Asignación de roles a usuario - frontend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#20]
asignar los roles a los usuarios, los de capitan y demas etc

**Comment by rubsuadav** [comment]
falta modificar acceso a endpoints en función de los roles, además también hemos arreglado el problema del logout cuando expira la sesión

**Comment by rubsuadav** [comment]
falta arreglar un error de actualizar al usuario

**Comment by rubsuadav** [comment]
error arreglado
