### ISSUE TITLE
Arreglar y crear algunos tests

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#30]
Hay un problema con las pruebas automaticas, arreglar los tests y hacer algunos probando funcionalidades acabadas como las de socio que prueben mockeando el backend.

**Comment by rubsuadav** [comment]
Se ha analizado la tarea y se ha concluido que su desarrollo es inviable en el tiempo que tenemos debido a dificultades ténicas

**Comment by rosmolarr** [comment]
Marco la issue como won't fix y la cerramos momentáneamente.
