### ISSUE TITLE
Registro de turnos - frontend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#48]
Se debe desarrollar la parte de front de su respectiva tarea de back, es decir, una sección de turnos en la navbar, un botón de creación y su formulario correspondiente.
Fecha límite: domingo 26/03

**Comment by cardelbec** [comment]
No lo pone así que voy a preguntar por si acaso, incluye la asignación de voluntarios a turnos o eso se le ha asignado a otra persona?

**Comment by cardelbec** [comment]
Daily: he dejado preparado todo lo que hace falta de la tarea para cuando Juanjo acabe la tarea del back poder probar si funciona la lista y el formulario y hacer la pull request

**Comment by cardelbec** [comment]
Daily: he conectado todo pudiendo probarlo ya con el backend que ha terminado Juanjo y he hecho la pull request

**Comment by cardelbec** [comment]
Daily: ya está terminado y me lo ha mergeado Rick en develop
