### ISSUE TITLE
Gestión de socios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#5]
Tarea backend: ISPP-2023-NGO-P3/backend-aiding#4

Se pide realizar la página principal de la organización siguiendo los siguientes consejos:

- Paleta de colores: [paleta bosco](https://colorhunt.co/palette/f5eddccfd2cffa9494eb1d36)
- Seguir los mockups: 
![Image](https://user-images.githubusercontent.com/80246352/222395675-fb021b00-6253-407d-b701-d14fe10181f3.png)
- Investigar plantillas

**Estos son los requisitos que hacen referencia al frontend de socios.**
<html>
<body>

ID | Prioridad | Título | Descripción
-- | -- | -- | --
RF-01 | Primario | Socios. | El sistema debe almacenar los siguientes datos de cada socio: nombre, apellido, dni, teléfono, correo electrónico, provincia, IBAN, si está dado de alta o no, la periodicidad de sus donaciones y la cantidad que dona. 
RI-04 | Primario | Comunicaciones. | El sistema debe almacenar la siguiente información de cada comunicación: fecha, tipo, socio y descripción. 

</body>
</html>

**Comment by Josdelsan** [comment]
Cosas que faltan por añadir:

- Validación de DNI e IBAN en el frontend.
- Página de error 404 cuando se busque un id que no existe (para crear, actualizar y detalles).
- Mensajes de error y gestión de errores en general (depende de que el backend devuelva los códigos correctos).
- Parsear los enumerate para que se vean correctamente en español.

**Comment by rosmolarr** [comment]
Darle una vuelta a el detalles de socio.
