### ISSUE TITLE
Gestión de usuarios

### ISSUE THREAD

**Issue by lNoelia** [ISPP-2023-NGO-P3/frontend-aiding#55]
Continuación de la issue #1 en la que se pide completar la gestión de usuarios.

**Comment by Josdelsan** [comment]
Cuando se registra no inicia sesión automáticamente, te redirige al login y hay que iniciar. Se ha hecho así porque habia que anidar 3 promesas y empezó a dar fallo. Para no echarla 5 horas a la tarea basicamente.
