### ISSUE TITLE
Compartir la aplicación en las redes sociales - Frontend

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#59]

**Comment by lNoelia** [comment]
Permitir a un usuario darle click a un boton (con una red social) que permita poner un post ( twitter, facebook, instagram ?) que enlace a nuestra aplicación

**Comment by marinaramirofde** [comment]
He realizado una investigación acerca de cómo postear en redes sociales a partir de un botón desde tu propia web. Tras eso he creado una cuenta de desarrolladores en Twitter para Aiding, he registrado la empresa en Twitter y he obtenido los tokens y keys necesarias para poder usar la API de Twitter. Me he decantado por esa porque es la que he visto más accesible.

No descarto probar con otras APIs más adelante.
