### ISSUE TITLE
Gestión de inventario

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#60]
Diseñar el apartado de front correspondiente a la gestión de inventario, solo los administradores deben poder acceder a esta funcionalidad.
**Fecha de finalización requerida: Viernes 7 de abril a las 23:59**

**Comment by nicsanmen** [comment]
Lo tengo muy encaminado, cogiendo de ejemplo usuarios y partners pero no lo terminé aún entre hoy y mañana lo intentaré dejar subido :D

**Comment by nicsanmen** [comment]
Lo tengo todo hecho a falta de saber dónde y cómo poner el botón y la gestión de crear los tipos, no sé si debo de hacerlo como están las comunicaciones de los partners, en otra vista o cómo

**Comment by nicsanmen** [comment]
ya está terminado esperando a que se revise, voy a grabar el vídeo y a pasarselo a Marcos
