### ISSUE TITLE
Gestionar notificaciones en módulos

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#62]

**Comment by mansanrod4** [comment]
Formulario para mandar notificaciones por correo. La idea es que en los listados de socios o voluntarios se marquen y que al darle a un botón se redirija a este formulario con el campo receptores completado. 
![image](https://user-images.githubusercontent.com/44496070/230791818-9634eb2e-60d4-43e7-bb3c-c84d789294f0.png)
