### ISSUE TITLE
Arreglar bugs encontrados

### ISSUE THREAD

**Issue by lNoelia** [ISPP-2023-NGO-P3/frontend-aiding#64]
- [x] El lnk de contacta con nosotros esta puesto como un href y recarga la pagina
- [x] Cuando no encuentra la direccion da un error que no es entendible por el usuario
- [x] Aparece los botones de editar y borrar en show de evento aunque no esté logeado
- [x] Botones de socio tienen un color raro y se solapan
- [x] Al crear voluntario no se pone lo de camion y tal, solo en el update
- [x] La página de inicio el link de mayores no funciona
- [x] Arreglar el icon
- [x] En recursos la fecha se ve sin formatear
- [x] Crear donación da un fallo
- [x] Cambiar filtros en las tablas al español, por ejemplo, reset, filter, search..
- [x] Añadir antiSpam de Rubén.
- [x] En voluntarios, cuando se deja el campo de telefono vacio, salta el error dos veces.
- [x] Cambiar estética, poner la navbar en negrita, y los datos en las views también.
- [x] Que los eventos se vean bien desde el móvil.
- [x] En voluntarios, verificar todos los cambios, teléfono, etc, que no están validados.
- [x] Revisar la validación de fechas en eventos (que la fecha de fin no sea antes que hoy ni que la fecha de inicio, por ejemplo)
- [x] Revisar validaciones en todos los formularios, añadirles el spam.
- [x] Revisar idioma en toda la app, por ejemplo tablas, como se puso arriba.
- [x] En voluntarios, a veces, sale un bug que no te deja crear mas, hay que mirarlo.
- [x] Revisar que los voluntarios inactivos no pueden asociarse a turnos, eso se vio como bug pero no se si se arregló.
- [x] Si creas un evento con fecha de 2023 se rompe la app.
- [x] Cuando creas un usuario con un username existente no se valida 
- [x] **MUY IMPORTANTE, MIRAR EL BUG DE EDITAR USUARIOS**
- [x] A usuarios piloto no les funcionaba turnos, probar y arreglarlo.
- [x] Si pones una calle que no existe, no sale el error entendible para el usuario.
- [x] Quitar los numeros de voluntarios, se deben agregar automaticos como en socios.
- [x] Validar las poblaciones en voluntarios y socios, se pueden meter que no existen.
- [ ] Que las tablas se vean bien desde el móvil.
- [ ] Intentar que la tabla de socios se vea bien en el móvil.

**Comment by rosmolarr** [comment]
Cambiado los botones, y arreglado el problema de donación, se habia borrado parte del código ya hecho por no hacer merge.

**Comment by rosmolarr** [comment]
Para cambiar lo que aparece en la pestaña, hay que hacerlo desde el archivo index.html dentro de public

**Comment by rosmolarr** [comment]
He logrado que el logo no se deje de ver

**Comment by rosmolarr** [comment]
He arreglado la recarga del footer. Daba problemas al intentar usar el navigate porque el _<footer/>_ no estaba dentro del router en **app.js**, basicamente para usar un hook en un componente, este debe estar dentro de un componente _<router/>_

**Comment by rosmolarr** [comment]
He arreglado la creación de voluntarios y ahora cuando se accede a una página sin permisos o a una url que no existe, se marca un error

**Comment by rosmolarr** [comment]
He añadido algunas mejoras que pidieron los usuarios piloto, como un botón para volver atrás, y también ya esta activa la edición de donaciones.

**Comment by rosmolarr** [comment]
He arreglado la vista de user, el idioma en partners, y también los validadores en eventos

**Comment by rosmolarr** [comment]
### Se vuelve a abrir la issue para arreglar todos estos problemas

- [ ] Cambiar filtros en las tablas al español, por ejemplo, reset, filter, search..
- [ ] Añadir antiSpam de Rubén
- [ ] A usuarios piloto no les funcionaba turnos, probar y arreglarlo
- [ ] Si pones una calle que no existe, no sale el error entendible para el usuario
- [ ] En voluntarios, cuando se deja el campo de telefono vacio, salta el error dos veces 
- [ ] Quitar los numeros de voluntarios, se deben agregar automaticos como en socios
- [ ] Validar las poblaciones en voluntarios y socios, se pueden meter que no existen
- [ ] Cambiar estética, poner la navbar en negrita, y los datos en las views también
- [ ] Que los eventos se vean bien desde el móvil.
- [ ] Que las tablas se vean bien desde el móvil.
- [ ] En voluntarios, verificar todos los cambios, teléfono, etc, que no están validados
- [ ] En voluntarios, a veces, sale un bug que no te deja crear mas, hay que mirarlo
- [ ] **MUY IMPORTANTE, MIRAR EL BUG DE EDITAR USUARIOS**

**Comment by nicsanmen** [comment]
He resuelto la mayoría de mis bugs, otros he comprobado que no petaban o no sé si me falta info, como el de que si se pone un evento con fecha de 2023 se rompe la app. No me ha pasado. 
Sólo me queda el de mirar el bug de editar usuario que entiendo que es el de la contraseña, mañana lo haré para tenerlo el domingo y subo todo junto.

**Comment by Rick3600** [comment]
Numero de voluntario arreglado, ha sido sustituido en las tablas por el id y no se puede poner manualmente ni modificar, se genera automaticamente al ser el ID

**Comment by Rick3600** [comment]
Añadida nueva validación para el atributo place de voluntarios

**Comment by Rick3600** [comment]
En mi máquina si funciona el crear nuevos turnos

**Comment by nicsanmen** [comment]
En principio ya están resueltos todos mis bugs. Porfa cuando se comprueben que me digan porque he hecho pruebas y en principio todo okay, pero si hubiese algún fallo pues para corregirlo cuanto antes.

**Comment by rubsuadav** [comment]
De los bugs generales de anteriores sprints se han solucionado casi todos ya: lo del envío de las notificaciones hay veces que acierta y otras veces falla (suele ser cuando pones correos gmail cuando falla y no de la us) he estado investigando el bug y es debido al temporizador, previamente sale el error del swal rojo que debugeando la consola sale esto:


![Image](https://user-images.githubusercontent.com/80253875/236541429-61cb8527-d349-4e05-9dfb-f3f6aa7bdfdc.png)

aqui se aprecia una peticion amterior del envio de notificaciones con codigo 200 OK mientras que el otro no da codigo HTTP debido a que al mirar la consola sale error del timeout del tiempo de envio de la petición, tras eso, pasado unos 10 min más o menos llega el correo, aquí la captura:


![Image](https://user-images.githubusercontent.com/80253875/236542109-af81017d-6be0-46be-97c0-e9e98409eeab.png)

**Comment by rubsuadav** [comment]
Además de los bugs mencionados por @cardelbec de la app de bosco: tenemos este progreso:

**MÓDULO VOLUNTARIOS**

- [ ] Como administrador he intentado editar un voluntario poniendo en el NIF algo que no tiene formato de NIF, y el error que me ha salido es "Ya existe un voluntario con ese NIF, teléfono o email" cuando eso no es lo que falla.
- [ ] Como administrador he intentado editar un voluntario poniendo en el código postal algo que no tiene formato de código postal, y aunque no me ha dejado guardarlo tampoco me ha salido ningún mensaje de error.
- [ ] Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones a todos los voluntarios a través de la lista de voluntarios. (bug comentado en el comentario de arriba de porque falla y una posible solución)

**MÓDULO BASE**

- [ ] Como administrador no me ha permitido editar un usuario poniendo mal su contraseña, pero tampoco me ha salido ningún mensaje de error.
- [ ] Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones manualmente a través del botón del menú de administración, y no han llegado los correos.
- [ ] Como administrador puedo acceder a un menú de "Atención al cliente" que me lleva a un listado, pero no hay botones para crear entidades de ningún tipo (no sé si esto es por error o queriendo) (si haces click en la tabla te debe de permitir poder responder a una solicitud de atención al cliente, dejando cambiar su estado respondido a true, pero si es verdad que si no hay ninguno al clickar en el show e intentar actualizar su estado peta y es un bug) 
- [ ] Como administrador me ha permitido modificar una consulta que ya estaba creada en el menú de "Atención al cliente" permitiéndome modificar su estado de Contestado (no sé si esto es por error o queriendo) (esto no es un bug)

**SOCIOS**

- [ ] Como administrador al poner letras con tilde o la letra Ñ en el nombre, apellido, dirección, pueblo/ciudad y provincia al editar un socio me los detecta como caracteres especiales y no me permite guardarlo.

- [ ] Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones a todos los socios a través de la lista de socios. (mismo problema)

**Comment by rubsuadav** [comment]
A día de hoy tras solucionar los 2 bugs que quedaban de bosco solucionaré los de DM:

Como usuario ADMINISTRADOR

- [ ] No me ha permitido crear un usuario con privilegios de administrador, el usuario que se crea tiene rol USUARIO aunque, en el formulario, se marque la opción Administrador.

- [ ] No me permite ver los datos de las reservas de un evento.

- [ ] No se permite crear o editar recursos y eventos SIN NÚMERO en la dirección.

- [ ]  No me permite crear un usuario introduciendo muchos caracteres en el nombre de usuario, mostrando un error genérico.

- [ ] Me permite crear un usuario introduciendo muchos caracteres en la contraseña, luego ese mismo usuario no se puede editar.

- [ ] Me permite acceder al formulario de edición de un evento ya iniciado. Se muestra el error "La dirección es inválida" cuando se intenta editar. (Aunque desde el back dice que es por estar activo)

- [ ]  No me permite mandar una notificación con muchos caracteres en el asunto y/o en el mensaje. Da un error genérico y sin comprobarse los campos del formulario.

**Comment by rubsuadav** [comment]
Se ha solucionado un gran bug que era cuando hacias click en la tabla de sin datos podias editar y mostrar datos de algo inexistente (del tema show no habia problemas pero estaba feo y del tema update si porque daba bugs)

**Comment by rubsuadav** [comment]
Por último, una vez solucionados esos bugs procederé a solucionar los del banco de alimentos:

- [ ] Como administrador no me ha permitido editar un usuario poniendo mal su contraseña, pero tampoco me ha salido ningún mensaje de error.

- [ ] Como supervisor no me deja enviar notificaciones a voluntarios.

- [ ] Como capitan no me deja enviar notificaciones a voluntarios.

- [ ] Como supervisor y capitan he creado un turno y le he asignado un voluntario, al hacer clic en completar borrador me da un error genérico, por lo que no se pueden crear turnos con voluntarios asignados(puede que esté conectado con las notificaciones porque al completar un borrador se debe mandar una notificación a los voluntarios asignados)

- [ ] Como admin me ha dejado crear tipos de items con el mismo nombre, he creado los siguientes "Lacteo", "lacteo", "Lácteo"

- [ ] Como admin me ha dejado crear tipos de items con nombres demasiado largos, concretamente he podido crear sin problemas uno con 2927 caracteres

- [ ] Como admin al crear un item hay una errata en el formulario, pone Tipos en vez de Tipo

- [ ] Como admin al crear un item si lo creo con cantidad 200000000000000000000000000000000000000000000 salta un error genérico.

**Comment by rubsuadav** [comment]
Estado de la tarea:
De los bugs a solucionar he solucionado un gran bug que era que el logotipo de vez en cuando cuando navegébamos entre los menús o se recargaba la página desaparecía el logotipo

**Comment by rubsuadav** [comment]
Actualización de la tarea:
Todos los bugs solucionados a excepción del último del correo de carlos muller debido a un debate que se debe de hacer en la reunión del día 13/05/2023 para buscar la mejor solución de las 2 posibles para evitar ese bug
