### ISSUE TITLE
Turnos y voluntarios

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/frontend-aiding#65]
Se debe diseñar el apartado de front de la correspondiente tarea asociada al back, básicamente es la asignación de un voluntario a un turno, solo un usuario con rol de supervisor debe tener acceso.
**Fecha de finalización requerida: Viernes 7 de abril a las 23:59**

**Comment by cardelbec** [comment]
Daily: la tarea va avanzando bien, ya he implementado la funcionalidad de asignar un voluntario a un socio. Me falta la de eliminar un voluntario asignado y cambiar el listado de voluntarios que aparecen en los detalles de un turno cuando rick cambie lo que le he pedido del back

**Comment by Manueldm01** [comment]
Como supervisor solo se deben ver los turnos que yo he creado además de que no se muestren los turnos que ya han pasado.

**Comment by cardelbec** [comment]
Daily: la tarea avanza bien, me falta gestionar que solo se puedan acceder a las vistas de turnos como Supervisor/Capitán y un par de retoques visuales para que quede mejor.
