### ISSUE TITLE
Exportación con filtrado de Socios

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#8]

**Comment by rubsuadav** [comment]
Se usará la librería antd-table-saveas-excel para la exportación de socios

**Comment by rubsuadav** [comment]
El progreso no está al 100% debido a que en el frontend de socios falta adaptarlo a los atributos

**Comment by rubsuadav** [comment]
Puesto que el filtrado no funcionaba con esa librería se ha tenido que cambiar a la librería xlsx

**Comment by rosmolarr** [comment]
Hablar con @rosmolarr para ponerse de acuerdo con el filtrado de socios.

**Comment by rubsuadav** [comment]
Ya se ha adaptado la exportación a lo indicado por rosa, a la espera de revisión de la tarea
