### ISSUE TITLE
Apuntarse a evento

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/frontend-aiding#81]

**Comment by rubsuadav** [comment]
Tarea realizada exitosamente validando todas las posibles RN incumbidas en dicha tarea.

**Comment by rubsuadav** [comment]
Opino que para rematar esta funcionalidad estaría bien que tras apuntarse al evento se generase una entrada con los datos del solicitante al evento que se ha inscrito.
