### ISSUE TITLE
Generación de certificados

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/frontend-aiding#9]
Usando word y pdf, con la pantilla mandada por bosco, realizar una generación de pdf con los datos de los socios y la documentación.

<html>
<body>

ID | Prioridad | Titulo | Descripción
-- | -- | -- | --
RF-08 | Primario | Generar certificado para cada socio. | El sistema debe permitir generar un certificado para cada socio que justifique el número de donaciones que hace al año.
RI-03 | Primario | Certificados. | El sistema debe generar certificados con los siguientes campos: nombre, apellido, DNI, provincia y nº de donaciones al año.
RN-03 | Primario | Certificados no modificables. | El sistema no permitirá editar los certificados generados.

</body>
</html>

**Comment by marolmmar1** [comment]
Mejoras planteadas para este sprint:
-El pdf por defecto generado estará en el lenguaje preferido del usuario: 10%
-Las imágenes del pdf tengan una referencia actualizada: 15%
-El pop up del link será un div con posición absoluta, para que salte independientemente de que haya un error o no: 50%
-Dar una opción de link de descarga para poder descargar el pdf si falla el visualizador: 25%
