### ISSUE TITLE
Tests frontend

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/frontend-aiding#94]

**Comment by lNoelia** [comment]
Realizar test exploratorios pre-separacion de la aplicacion y post- separacion de la aplicacion en 3 partes

**Comment by cardelbec** [comment]
Daily: he realizado test exploratorios pre-separación de las aplicaciones. Aquí detallo todo lo que he probado y lo que he encontrado:

MÓDULO DE VOLUNTARIOS
Como admin me deja crear usuarios capitan/supervisor 
Como admin me deja crear voluntarios en el menú de voluntarios 
Como admin NO me ha dejado enviar una notificación a los voluntarios, me ha salido Unauthorized: /base/notifications/
en la consola del backend
Como capitán me sale el botón de Voluntarios en el menú, y en el listado está el botón de Crear Voluntario pero si le doy
me redirige a la página de inicio, lo mismo con el botón de notificar a voluntarios
Como capitán puedo acceder al menú de Turnos y crearlos. En el listado de turnos puedo entrar a la vista de detalles de
turnos, donde puedo editar sus atributos, asignar/desasignar voluntarios y borrar el turno. Lo que NO me ha permitido
es quitar el modo borrador, en la consola del backend sale un error de SMTP, probablemente no funcione porque llama a la 
función de enviar notificación, que tampoco me funcionaba como administrador.

MÓDULO BASE
Como usuario anónimo me ha permitido registrarme con nombre de usuario "Usuario1" y contraseña "Usuario1" 
Como usuario anónimo he intentado registrarme con un nombre de usuario muy largo, y el mensaje de error que me ha dado ha sido genérico
Como usuario anónimo me he registrado con nombre de usuario "Usuario3" y contraseña "c", la contraseña claramente siendo
demasiado corta
Como usuario admin puedo crear a través del menú de Usuario usuarios no administradores y usuarios administradores, presentando los mismos problemas que en las pruebas anteriores (me deja poner contraseñas demasiado cortas y el nombre demasiado largo da error genérico)

MÓDULO DE RECURSOS
Como admin me ha permitido crear un recurso en el menú Recursos. Pasa como con el módulo base, si pongo los atributos demasiado largos me sale un error genérico en lugar de decirme que he puesto el atributo demasiado largo.
Como usuario anónimo he podido acceder al menú de Recursos y ver el recurso que había creado como admin previamente, aparece correctamente la dirección en el mapa 

MÓDULO DE NOTICIAS
Como admin me ha permitido crear una noticia nueva en el menú de Noticias. Si dejo la sección vacía el mensaje de error que sale es "Ha habido un error con la sección", probablemente debería poner que no se puede dejar vacía o algo por el estilo.
Como usuario anónimo puedo acceder al menú de Noticias. Me permite filtrar por todas las secciones o por la que cree previamente como administrador, y puedo acceder a la noticia que he creado. En la vista de detalles de la noticia puedo ver las noticias de la misma sección.

**Comment by Manueldm01** [comment]
MÓDULO DE NOTICIAS
Como admin he editado una noticia y le he puesto una cadena de 75240 caracteres y me ha dejado hacerlo y en el front se ve mal en los detalles de la noticia, esto ocurre si hay una palabra más larga que el ancho de la tarjeta de detalles.

**Comment by juaalvcam** [comment]
Estos son los errores encontrados durante los test de exploración:

-Al crear un usuario desde la aplicacion el boton de que sea administrador no funciona
-Desde la interfaz de usuarios, al entrar en un usuario y querer editarlo funciona correctamente, al darle a editar me aparece una contraseña con muchos caracteres
-Al logearme como capitan no me aparece el menu para capitanes/supervisores
-Al crear una noticia si una palabra es demasiado grande la noticia se extiende en la horizontal sin hacer saltos de linea
-No me deja actualizar la fecha de un evento finalizado para ampliar el plazo al editarlo "Bad Request: /events/2"

**Comment by cardelbec** [comment]
He estado realizando test exploratorios post separación de la aplicación, esto es lo que he encontrado:

BANCO DE ALIMENTOS
Como administrador, me ha permitido sin problemas crear usuarios con roles capitan/supervisor.
**Como administrador, me ha permitido crear un voluntario, pero al intentar crear un segundo me ha salido el error "Ya existe un voluntario con ese NIF, e-mail o teléfono" a pesar de que el voluntario que cree inicialmente tenía esos tres campos diferentes.**
**Como administrador, la opción "Atención al cliente" del menú es completamente inútil, me enseña una tabla vacía y no hay botones para hacer nada.**
Como administrador, me ha permitido crear item y tipos de item sin ningún problema.
**Como administrador, no me ha permitido enviar notificaciones de ningún tipo, ni poniendo manualmente los correos ni haciéndolo desde la lista de voluntarios.**

Como capitán, me ha permitido crear un turno, editar sus atributos y borrarlo.
Como capitán, me ha permitido añadir voluntarios y quitarlos de un turno.
**Como capitán, no me ha permitido crear un segundo voluntario (ya había creado uno), me ha salido el error "Ya existe un voluntario con ese NIF, e-mail o teléfono" a pesar de que el voluntario que cree inicialmente tenía esos tres campos diferentes.**
**Como capitán no me ha permitido quitar el modo borrador de un turno.**
**Como capitán, no me ha permitido enviar notificaciones de ningún tipo, ni poniendo manualmente los correos ni haciéndolo desde la lista de voluntarios.**

**Comment by Manueldm01** [comment]
He estado realizando test exploratorios post separación de la aplicación, he puesto en negrita todo lo que ha fallado, esto es lo que he encontrado:
BOSCO:
Como admin me ha dejado crear 2 voluntarios.
Como admin me ha dejado dar de alta a un socio.
Como usuario me ha dejado contactar mediante la atención al cliente.
Como admin me ha dejado editar la respuesta a la atención al cliente.
Como admin me ha dejado crear y editar a un usuario sin ningún problema.

**Como admin no me deja crear usuarios supervisores ni capitanes.
Como admin no me deja enviar notificaciones a los voluntarios dados de alta, dice que hay un error al crear la notificación.**

DOÑA MARIA:
Como admin he probado a inscribirme en un evento hasta llenar la capacidad y ha funcionado.
Como usuario he intentado inscribirme a un evento completo desde la url y no me ha dejado.

**Como admin he editado una noticia y si la descripción contiene una palabra más larga que el ancho de la tarjeta de detalles se sale de la tarjeta.
Como admin he probado a crear un evento con 0 plazas y me ha dejado.**

**Comment by lNoelia** [comment]
Manu D :  tests exploratorios del banco de alimento 
Carlos  : tests  exploratorios de Bosco global 
Manu S : tests exploratorios de Doña María 

Intentad seguir el formato que se muestra arriba y poner los bugs encontrados en #bugs en discord también

**Comment by cardelbec** [comment]
He estado realizando test exploratorios de la aplicación de Bosco, **he puesto en negrita todo lo que ha fallado**, esto es lo que he encontrado:

MÓDULO DE VOLUNTARIOS
Como administrador me ha permitido crear y editar voluntarios si no pongo cosas raras en los campos sin problemas.
**Como administrador he intentado editar un voluntario poniendo en el NIF algo que no tiene formato de NIF, y el error que me ha salido es "Ya existe un voluntario con ese NIF, teléfono o email" cuando eso no es lo que falla.**
**Como administrador he intentado editar un voluntario poniendo en el código postal algo que no tiene formato de código postal, y aunque no me ha dejado guardarlo tampoco me ha salido ningún mensaje de error.**
**Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones a todos los voluntarios a través de la lista de voluntarios.**

MÓDULO BASE
Como administrador me ha permitido crear y editar voluntarios sin poner cosas raras en los campos sin problemas.
**Como administrador no me ha permitido editar un usuario poniendo mal su contraseña, pero tampoco me ha salido ningún mensaje de error.**
**Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones manualmente a través del botón del menú de administración, y no han llegado los correos.**
**Como administrador puedo acceder a un menú de "Atención al cliente" que me lleva a un listado, pero no hay botones para crear entidades de ningún tipo (no sé si esto es por error o queriendo)**
**Como administrador me ha permitido modificar una consulta que ya estaba creada en el menú de "Atención al cliente" permitiéndome modificar su estado de Contestado (no sé si esto es por error o queriendo)**

MÓDULO DE SOCIOS
Como administrador me ha permitido crear y editar socios sin poner cosas raras en los campos sin problemas.
**Como administrador al poner letras con tilde o la letra Ñ en el nombre, apellido, dirección, pueblo/ciudad y provincia al editar un socio me los detecta como caracteres especiales y no me permite guardarlo.**
**Como administrador me ha salido un mensaje de error genérico al intentar enviar notificaciones a todos los socios a través de la lista de socios.**
Como administrador me permite crear Comunicaciones asociadas a socios sin problemas. Me permite crear Comunicaciones con fechas futuras, no se si debería permitirlo.
Como administrador me ha permitido crear y editar la donación de un socio sin problemas.
Como administrador me ha permitido generar los recibos en español y en catalán sin problema, modificándose la cantidad total si modifico la cantidad de la donación.
Como administrador me ha permitido exportar socios sin problemas.

GENERAL
A veces cuando se recarga la página el logo de Bosco de la esquina superior izquierda no carga

**Comment by mansanrod4** [comment]
He estado realizando test exploratorios de la aplicación de Doña María:
Como administrador:
- No me ha permitido crear un usuario con privilegios de administrador, **el usuario que se crea tiene rol USUARIO aunque, en el formulario, se marque la opción Administrador**.
- Al editar un usuario, si se introduce mal la contraseña actual, no se muestra qué está fallando.
- No me permite ver los datos de las reservas de un evento.
- No se permite **crear o editar recursos y eventos SIN NÚMERO** en la dirección. 
- Me permite crear y editar una noticia.
- Me permite crear y borrar una sección de noticias

Como usuario sin permisos:
- Me permite apuntarme a un evento.
- Me permite hacer una reserva con el mismo número de teléfono, **no me da información sobre si había ya una reserva con ese número**.

**Comment by Manueldm01** [comment]
He realizado test exploratorios sobre el despliegue del banco de alimentos, he encontrado lo siguiente:

Positivo
Como supervisor he podido crear un turno correctamente.
Como supervisor he intentado añadir un voluntario inactivo a un turno, no me ha dejado y me ha mostrado el mensaje correcto.
Como supervisor me ha dejado eliminar el turno sin problema.
Como capitan he podido crear un turno correctamente.
Como capitan he intentado añadir un voluntario inactivo a un turno, no me ha dejado y me ha mostrado el mensaje correcto.
Como capitan me ha dejado eliminar el turno sin problema.
Como capitan he probado los filtros y funcionan a la perfeccion.
Como usuario no registrado me ha dejado registrarme correctamente.
Como usuario logueado he intentado acceder donde no debía y no me ha dejado.
Como admin me ha dejado varios tipos de item correctamente y no me ha dejado crearlo duplicado.

Negativo
Como administrador no me ha permitido editar un usuario poniendo mal su contraseña, pero tampoco me ha salido ningún mensaje de error.
Como supervisor no me deja enviar notificaciones a voluntarios.
Como capitan no me deja enviar notificaciones a voluntarios.
Como supervisor y capitan he creado un turno y le he asignado un voluntario, al hacer clic en completar borrador me da un error genérico, por lo que no se pueden crear turnos con voluntarios asignados(puede que esté conectado con las notificaciones porque al completar un borrador se debe mandar una notificación a los voluntarios asignados)
Como admin me ha dejado crear tipos de items con el mismo nombre, he creado los siguientes "Lacteo", "lacteo", "Lácteo"
Como admin me ha dejado crear tipos de items con nombres demasiado largos, concretamente he podido crear sin problemas uno con 2927 caracteres
Como admin al crear un item hay una errata en el formulario, pone Tipos en vez de Tipo
Como admin al crear un item si lo creo con cantidad 200000000000000000000000000000000000000000000 salta un error genérico.
